// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go_for_spring_developer/10-dependency-injection/e1/bean"
)

// Injectors from wire.go:

func initializeUserService() *bean.UserService {
	userRepository := bean.NewUserRepository()
	userService := bean.NewUserService(userRepository)
	return userService
}
