// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	bean2 "go_for_spring_developer/10-dependency-injection/e3/bean"
)

// Injectors from wire.go:

func initializeUserService() *bean2.UserService {
	userRepository := bean2.NewUserRepository()
	userService := bean2.NewUserService(userRepository)
	return userService
}
